import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Restaurant X Case Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar /> 
      <main className={styles.main}>
       <div>
         <h1>Webflow - Jamstack- Shopify Restaurant Project</h1>
         <p>
4 minute read
         </p>
         <p>
          Restaurant X is an online restaurant that offers high quality meals with freshly picked and sourced ingredients to provide exquisite taste experience. The goal was to migrate existing Webflow Shopify theme to a more customizable archictecture that will allow client to expand menu options and scale in future
         </p>
       </div>
       
       <div className={styles.description}>
        <div>
          <h2>Type</h2>
          <p>
            E-commerce Restaurant 
          </p>
        </div>
        <div>
          <h2>Stack</h2>
          <p>Next Js</p>
          <p>11ty</p>
          <p>Shopify</p>
          <p>Netlify</p>
        </div>
        <div>
          <h2>Live</h2>
          <p>Project still under construction</p>
        </div>

       </div>

       <div className={styles.image1}>
       <Image src="/szn1.png" alt="site logo" width={600} height={500} />
       </div>
       <div>
        <h1>Project Purpose and Goal</h1>
        <p>Restaurant X is an online restaurant that offers high quality meals with freshly picked and sourced ingredients to provide exquisite taste experience. 
          The goal is to migrate existing Webflow Shopify theme to a more customizable archictecture that will allow client to expand menu options and 
          to scale in future. This posed a challenge for their Webflow themed site , and a new architectural structure had to be developed . </p>

       </div>
    
       <div>
        <h1>Web Architecture and Explanation</h1>
         <p className={styles.heady}> In selecting a framework ,i considered a few things... </p>
        <br/>
        <p>
          1.  What framework would allow me easily translate already written Webflow code? <br/>
          2.  What framework would allow for scalbility in the future? <br/>
          3.  What framework would allow for customization? <br/>
          4.  What framework would allow for a great user experience ie. fast load times? <br/>
          5.  What framework would allow me leverage the existing Shopify infrastructure? <br/> 
          <br/>
          I decided on using a decoupled <strong> Jamstack</strong> architectural approach utilizing <strong>Next Js</strong> as my <strong>static site generator </strong>,Shopify as my Headless cms /3rd party api and Netlify as my CDN which the site will be deployed to  {`(Content Delivery Network) `}due to the following reasons <br/> <br/> a. Ability to use Next Js {`( A powerful Static site generator) `}with ability for server side rendering for dynamic content <br/>b. I am very comfortable with the tools available in the JamStack ecosystem which allows for an easy transition of  Webflows code written in  html ,css,javascript <br/> c. Ability to easily connect to Shopify and fetch product data Via Api's <br/>
          d. Ability to <strong>test my changes locally </strong>before pushing to repo , Easily collaborate with Oke studios via comments on <strong> deploy previews</strong> , as well as <strong>continous integration and deployment </strong> capabilities {`(Anytime i make changes and push to my repo, changes are detected and an automatic deployment is triggered)`}. All made possible by deploying on <strong>Netlify Edge Network</strong> <br/>
          e. Ability to use a severless approach thanks to <strong>serverless functions{(`(Netlify functions)`)}</strong> for Apis that are commonly executed on a server . These functions are built into the Next js/Netlify Jamstack architecture 
        </p>
       </div>
       <div>
        <h1>Problems and Thought Process</h1>
        <p> Restaurant X contacted Oke Studios for a site redesign. They were looking to customize new features for client engagemnent. The problem they had was that the website  was created using a template webflow shopify theme, which did not allow for desired customization.
          Thats when I come in</p> <div className={styles.images}><br/> <Image src='https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmM0ZWNiYmZmODdmNzA2M2YwZTM3NjIwN2IyNTI0MWU4NGRhMGFkMyZjdD1n/l1gYcLBSdL7PoDsizo/giphy.gif' width={480} height={400} quality={100} /><br/> </div> 
          <p>I was brought into the project to by Oke Studios to figure out a way to meet the clients desire 
            to customize site regularly and keep using the Shopify platform. 
            My brain went to working, and to satisfy this request I suggested working with a decoupled architecture. 
            This method seperates the front-end and back-end systems , whcih would allow the front-end to be 
            fully customizable, as well as keep the products on Shopify.
         The front-end {`(NextJs)`}would receive data from <strong>Shopify via Shopify's storefront Api keys </strong><br/> <strong style={{color:'red' ,fontStyle:'italic'}}> *Sidenote i originally planned on using 11ty because I found a platform {`(Udesly)`} that transforms webflow code to Jamstack {`(11ty) code`}this might still be done ,stay tuned</strong>  😉. <br/> </p> 
         <p><strong>I mapped the data using GraphQL queries</strong> to build static pages and utilized next js server side rendering for dynamic data <br/> </p>
         <br/> <div className={styles.images}><Image src="/GraphqlImg.png" width={400} height={300}/></div>
         <br/><div className={styles.images}><Image src="/staticgeneration.png" width={400} height={300}/>
          <br/>  </div>
       </div>
       <div>
        <h1>Lessons Learned </h1>
        <p>The lessons are still ongoing. Currently testing out 11ty capabilites , and trying to figure out why my 11ty file wont load 😭 i'll keep y'all updated once project is complete </p>
       </div>
      </main>
      <Footer />
    </>
  )
}
